name: API Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/api/**'
      - 'tests/api/**'
      - '.github/workflows/api-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/api/**'
      - 'tests/api/**'
      - '.github/workflows/api-tests.yml'
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'API test suite to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - airports
          - distance
          - performance

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  # Ensure GITHUB_TOKEN has write permissions for Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install --with-deps

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run API Tests
        run: |
          python -m pytest tests/api/ -m api --alluredir=allure-results-api --html=api-test-report.html --self-contained-html

      - name: Upload API test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: |
            allure-results-api/
            api-test-report.html

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results-api -o allure-report-api --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-api
          path: allure-report-api/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report-api
          keep_files: true
          force_orphan: false

      - name: Notify API Test Results
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { data: jobs } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });

            const apiTestJob = jobs.jobs.find(job => job.name === 'API Tests');
            const status = apiTestJob?.conclusion === 'success' ? '✅' : '❌';

            const summary = `## API Test Execution Summary

            **Status**: ${status} ${apiTestJob?.conclusion === 'success' ? 'All API tests passed' : 'Some API tests failed'}

            **Test Suite**: Complete API test coverage
            **Environment**: Python ${{ env.PYTHON_VERSION }}, Playwright API

            **Results**:
            - Allure Report: https://${context.repo.owner}.github.io/${context.repo.repo}/
            - Test Artifacts: Available in workflow artifacts

            **Coverage**:
            - Airport endpoints validation
            - Distance calculations
            - Performance testing
            - Error handling validation`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue?.number || 0,
              body: summary
            });
